Normalize tag support
OpenTSDB/opentsdb pull request #1525
Opened 2019-02-06 05:31 UTC by gnydick

This new plugin type allows you to provide a plugin to normalize tags. My use case for implementing this is the fact that the slew of Cloud Native systems coming online all export their metrics slightly differently and opentsdb doesn't support fuzzy matches or specifying which tags are equivalent to each other.

I was receiving container, container-name, container_name, etc., etc., etc.

This plugin type requires a normalizeTags(tags) method. The tags are passed in and a normalized set are returned.

2019-05-15 16:37 UTC, johann8384 requested changes

2019-05-15 16:37 UTC, johann8384 commented on configure.ac
> +AC_INIT([opentsdb], [2.4.0-tnp], [opentsdb@googlegroups.com])
We probably don't need this change.

2019-05-15 16:37 UTC, johann8384 commented on src/core/TSDB.java
> -import java.io.File;
So, it looks like you did the "auto format" in IntelliJ, I've been tempted to commit this myself. Would it be possible to isolate just the changes relevant to your new plugin type?

I love the concept and would be happy to get this merged if we can remove the unrelated changes.

2019-05-15 16:37 UTC, johann8384 commented on src/tsd/RTPublisher.java
> - * <b>Note:</b> Implementations must have a parameterless constructor. The
You can leave in all the "trailing whitespace" fixes if you want! :)

2019-05-15 16:41 UTC, gnydick commented on configure.ac
> +AC_INIT([opentsdb], [2.4.0-tnp], [opentsdb@googlegroups.com])
Sounds good!

2024-12-12 16:00 UTC, johann8384 commented
Merging in #2302. @gnydick I know it's been, um, years, but if you have an example of a working tag normalization plugin that would be great!

2024-12-12 16:00 UTC, closed without merging

2025-09-07 02:20 UTC, sins921 approved these changes

2025-09-07 03:38 UTC, gnydick commented
Let me see if I have an example for you...

2025-09-07 03:41 UTC, gnydick commented
Here's an example plugin.  https://github.com/OpenTSDB/opentsdb/commit/6aba0eda2dcf3dea1f390b2484cd00915e649abc

2025-09-07 07:42 UTC, sins921 approved these changes